{
 :start "Welcome to the Game. Type play to start or /help for a list of commands."
 :help "feed -- give your treats to the monster. pet -- caress the monster's neck. scold -- \"Who's the bad boy?\". hit -- flick the monster's nose and show who is the boss. tame -- try to tame the monster. You can only try once!"
 :stand-by "You are in front of the cage. Please wait for other students."
 :joined-game "A new student joined."
 :error-in-game "Why are you waiting? The monster is ready. Go on!"
 :error-out-of-game "The class hasn't started yet. Type play to start, then wait for your groupmates to join."
 :error "Your command seems off. Type /help for a list of commands."
 :start-of-the-game "Welcome, students, to your first Care of Magical Creatures class. In this cage, behind a curtain, is a monster for you. Your number one task is to not get eaten; to earn an A, please tame this little nice monster. Will it be a gentle niffler or a dangerous hippogriff, you ask? You'll get to know this first, I promise. You only have one try to tame the monster, because a monster does not just decline your offer -- it eats you instead. Find your own way of taming the monster first to win. Put on your gloves and take some treats. Don't forget: not everyone likes to be petted."
 :game-over-user-trying-action "Здесь могла бы быть ваша реклама, но это ваш некролог. Hogwarts will miss you"
 :tame "tried to tame"
 :hit "hits"
 :pet "strokes"
 :scold "scolds"
 :feed "gives a treat to"
 :good-ending "the monster becomes your new friend! It followed you until the end of the class, purring and leaning against you affectionately."
 :bad-ending "the monster swallows you whole. It roars at the top of its voice and licks its lips in the anticipation of another careless student."
 :pleased-monster "the monster seems content and purrs quietly. You must be doing fine."
 :angry-monster "the monster seems angry and bellows loudly. You better not do this anymore."
 :monster0 "black Niffler"
 :monster1 "lordly Hippogriff"
 :monster2 "blazing Phoenix"
 :monster3 "huge Dragon"
 :monster4 "timid Bowtruckle"
 :monster5 "white Griffin"
 :monster6 "sturdy Erumpent"
 }
